# Generated by Django 4.2 on 2024-07-22 11:20

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='userFiles/', validators=[api.models.validate_html_file]),
        ),
    ]
